apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: k8s-api
  namespace: k8s-demo
  labels:
    name: k8s-api
spec:
  replicas: 3
  selector:
    matchLabels:
      name: k8s-api
  template:
    metadata:
      labels:
        name: k8s-api
    spec:
      containers:
      - name: k8s-api
        image: 	registry.cn-shanghai.aliyuncs.com/lingbohome/k8s-api:0.03
        resources: 
          requests:
            cpu: 200m
            memory: 200Mi
          limits: 
            cpu: 1
            memory: 500Mi
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---

kind: Service
apiVersion: v1
metadata:
  name: k8s-api
  namespace: k8s-demo
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
  selector:
    name: k8s-api